/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Timestamp, Uint64, QueryMsg, MigrateMsg, EncryptedResponse, Hash } from "./Chat.types";
export interface ChatReadOnlyInterface {
  contractAddress: string;
  encKey: ({
    bindingHashPassword
  }: {
    bindingHashPassword: string;
  }) => Promise<Hash>;
  chat: ({
    addressA,
    addressB,
    recipient
  }: {
    addressA: string;
    addressB: string;
    recipient: string;
  }) => Promise<EncryptedResponse>;
  chatGuestList: ({
    addressA,
    addressB,
    recipient
  }: {
    addressA: string;
    addressB: string;
    recipient: string;
  }) => Promise<EncryptedResponse>;
  image: ({
    id,
    owner,
    recipient
  }: {
    id: number;
    owner: string;
    recipient: string;
  }) => Promise<EncryptedResponse>;
  imageWhitelist: ({
    id,
    owner
  }: {
    id: number;
    owner: string;
  }) => Promise<EncryptedResponse>;
  lastImageId: ({
    owner
  }: {
    owner: string;
  }) => Promise<EncryptedResponse>;
}
export class ChatQueryClient implements ChatReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.encKey = this.encKey.bind(this);
    this.chat = this.chat.bind(this);
    this.chatGuestList = this.chatGuestList.bind(this);
    this.image = this.image.bind(this);
    this.imageWhitelist = this.imageWhitelist.bind(this);
    this.lastImageId = this.lastImageId.bind(this);
  }
  encKey = async ({
    bindingHashPassword
  }: {
    bindingHashPassword: string;
  }): Promise<Hash> => {
    return this.client.queryContractSmart(this.contractAddress, {
      enc_key: {
        binding_hash_password: bindingHashPassword
      }
    });
  };
  chat = async ({
    addressA,
    addressB,
    recipient
  }: {
    addressA: string;
    addressB: string;
    recipient: string;
  }): Promise<EncryptedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      chat: {
        address_a: addressA,
        address_b: addressB,
        recipient
      }
    });
  };
  chatGuestList = async ({
    addressA,
    addressB,
    recipient
  }: {
    addressA: string;
    addressB: string;
    recipient: string;
  }): Promise<EncryptedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      chat_guest_list: {
        address_a: addressA,
        address_b: addressB,
        recipient
      }
    });
  };
  image = async ({
    id,
    owner,
    recipient
  }: {
    id: number;
    owner: string;
    recipient: string;
  }): Promise<EncryptedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      image: {
        id,
        owner,
        recipient
      }
    });
  };
  imageWhitelist = async ({
    id,
    owner
  }: {
    id: number;
    owner: string;
  }): Promise<EncryptedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      image_whitelist: {
        id,
        owner
      }
    });
  };
  lastImageId = async ({
    owner
  }: {
    owner: string;
  }): Promise<EncryptedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      last_image_id: {
        owner
      }
    });
  };
}
export interface ChatInterface extends ChatReadOnlyInterface {
  contractAddress: string;
  sender: string;
  prepareEncKey: ({
    bindingHash
  }: {
    bindingHash: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeBindingHash: ({
    bindingHash
  }: {
    bindingHash: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeBindingHashUnstable: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  sendMessage: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  storeImage: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  allowToReadChat: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  allowToReadImages: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  connectChat: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  disconnectChat: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  connectImages: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  disconnectImages: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerHub: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ChatClient extends ChatQueryClient implements ChatInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.prepareEncKey = this.prepareEncKey.bind(this);
    this.removeBindingHash = this.removeBindingHash.bind(this);
    this.removeBindingHashUnstable = this.removeBindingHashUnstable.bind(this);
    this.sendMessage = this.sendMessage.bind(this);
    this.storeImage = this.storeImage.bind(this);
    this.allowToReadChat = this.allowToReadChat.bind(this);
    this.allowToReadImages = this.allowToReadImages.bind(this);
    this.connectChat = this.connectChat.bind(this);
    this.disconnectChat = this.disconnectChat.bind(this);
    this.connectImages = this.connectImages.bind(this);
    this.disconnectImages = this.disconnectImages.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  prepareEncKey = async ({
    bindingHash
  }: {
    bindingHash: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      prepare_enc_key: {
        binding_hash: bindingHash
      }
    }, fee, memo, _funds);
  };
  removeBindingHash = async ({
    bindingHash
  }: {
    bindingHash: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_binding_hash: {
        binding_hash: bindingHash
      }
    }, fee, memo, _funds);
  };
  removeBindingHashUnstable = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_binding_hash_unstable: {}
    }, fee, memo, _funds);
  };
  sendMessage = async ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      send_message: {
        data,
        timestamp
      }
    }, fee, memo, _funds);
  };
  storeImage = async ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      store_image: {
        data,
        timestamp
      }
    }, fee, memo, _funds);
  };
  allowToReadChat = async ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      allow_to_read_chat: {
        data,
        timestamp
      }
    }, fee, memo, _funds);
  };
  allowToReadImages = async ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      allow_to_read_images: {
        data,
        timestamp
      }
    }, fee, memo, _funds);
  };
  connectChat = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      connect_chat: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  disconnectChat = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      disconnect_chat: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  connectImages = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      connect_images: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  disconnectImages = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      disconnect_images: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  registerHub = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_hub: {}
    }, fee, memo, _funds);
  };
}