/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  prepare_enc_key: {
    binding_hash: string;
  };
} | {
  remove_binding_hash: {
    binding_hash: string;
  };
} | {
  remove_binding_hash_unstable: {};
} | {
  send_message: {
    data: string;
    timestamp: Timestamp;
  };
} | {
  store_image: {
    data: string;
    timestamp: Timestamp;
  };
} | {
  allow_to_read_chat: {
    data: string;
    timestamp: Timestamp;
  };
} | {
  allow_to_read_images: {
    data: string;
    timestamp: Timestamp;
  };
} | {
  connect_chat: {
    trade_id: number;
  };
} | {
  disconnect_chat: {
    trade_id: number;
  };
} | {
  connect_images: {
    trade_id: number;
  };
} | {
  disconnect_images: {
    trade_id: number;
  };
} | {
  pause: {};
} | {
  unpause: {};
} | {
  register_hub: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type QueryMsg = {
  enc_key: {
    binding_hash_password: string;
  };
} | {
  chat: {
    address_a: string;
    address_b: string;
    recipient: string;
  };
} | {
  chat_guest_list: {
    address_a: string;
    address_b: string;
    recipient: string;
  };
} | {
  image: {
    id: number;
    owner: string;
    recipient: string;
  };
} | {
  image_whitelist: {
    id: number;
    owner: string;
  };
} | {
  last_image_id: {
    owner: string;
  };
};
export interface MigrateMsg {
  version: string;
}
export interface EncryptedResponse {
  timestamp: Timestamp;
  value: string;
}
export interface Hash {
  bytes: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
}