/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, Timestamp, Uint64, QueryMsg, MigrateMsg, EncryptedResponse, Hash } from "./Chat.types";
export interface ChatMsg {
  contractAddress: string;
  sender: string;
  prepareEncKey: ({
    bindingHash
  }: {
    bindingHash: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeBindingHash: ({
    bindingHash
  }: {
    bindingHash: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeBindingHashUnstable: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  sendMessage: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  storeImage: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  allowToReadChat: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  allowToReadImages: ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  connectChat: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  disconnectChat: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  connectImages: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  disconnectImages: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  registerHub: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class ChatMsgComposer implements ChatMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.prepareEncKey = this.prepareEncKey.bind(this);
    this.removeBindingHash = this.removeBindingHash.bind(this);
    this.removeBindingHashUnstable = this.removeBindingHashUnstable.bind(this);
    this.sendMessage = this.sendMessage.bind(this);
    this.storeImage = this.storeImage.bind(this);
    this.allowToReadChat = this.allowToReadChat.bind(this);
    this.allowToReadImages = this.allowToReadImages.bind(this);
    this.connectChat = this.connectChat.bind(this);
    this.disconnectChat = this.disconnectChat.bind(this);
    this.connectImages = this.connectImages.bind(this);
    this.disconnectImages = this.disconnectImages.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  prepareEncKey = ({
    bindingHash
  }: {
    bindingHash: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          prepare_enc_key: {
            binding_hash: bindingHash
          }
        })),
        funds: _funds
      })
    };
  };
  removeBindingHash = ({
    bindingHash
  }: {
    bindingHash: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_binding_hash: {
            binding_hash: bindingHash
          }
        })),
        funds: _funds
      })
    };
  };
  removeBindingHashUnstable = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_binding_hash_unstable: {}
        })),
        funds: _funds
      })
    };
  };
  sendMessage = ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          send_message: {
            data,
            timestamp
          }
        })),
        funds: _funds
      })
    };
  };
  storeImage = ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          store_image: {
            data,
            timestamp
          }
        })),
        funds: _funds
      })
    };
  };
  allowToReadChat = ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          allow_to_read_chat: {
            data,
            timestamp
          }
        })),
        funds: _funds
      })
    };
  };
  allowToReadImages = ({
    data,
    timestamp
  }: {
    data: string;
    timestamp: Timestamp;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          allow_to_read_images: {
            data,
            timestamp
          }
        })),
        funds: _funds
      })
    };
  };
  connectChat = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          connect_chat: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  disconnectChat = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          disconnect_chat: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  connectImages = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          connect_images: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  disconnectImages = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          disconnect_images: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  registerHub = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_hub: {}
        })),
        funds: _funds
      })
    };
  };
}