/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = string;
export type QueryMsg = {
  hash_reproduceable: {
    user_password: string;
    user_salt: string;
  };
} | {
  hash_unique: {
    user_password: string;
    user_salt: string;
  };
} | {
  timestamp: {};
};
export interface MigrateMsg {
  version: string;
}
export interface Hash {
  bytes: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
}
export type Timestamp = Uint64;
export type Uint64 = string;