/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, Hash, Timestamp, Uint64 } from "./HashGenerator.types";
export interface HashGeneratorReadOnlyInterface {
  contractAddress: string;
  hashReproduceable: ({
    userPassword,
    userSalt
  }: {
    userPassword: string;
    userSalt: string;
  }) => Promise<Hash>;
  hashUnique: ({
    userPassword,
    userSalt
  }: {
    userPassword: string;
    userSalt: string;
  }) => Promise<Hash>;
  timestamp: () => Promise<Timestamp>;
}
export class HashGeneratorQueryClient implements HashGeneratorReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.hashReproduceable = this.hashReproduceable.bind(this);
    this.hashUnique = this.hashUnique.bind(this);
    this.timestamp = this.timestamp.bind(this);
  }
  hashReproduceable = async ({
    userPassword,
    userSalt
  }: {
    userPassword: string;
    userSalt: string;
  }): Promise<Hash> => {
    return this.client.queryContractSmart(this.contractAddress, {
      hash_reproduceable: {
        user_password: userPassword,
        user_salt: userSalt
      }
    });
  };
  hashUnique = async ({
    userPassword,
    userSalt
  }: {
    userPassword: string;
    userSalt: string;
  }): Promise<Hash> => {
    return this.client.queryContractSmart(this.contractAddress, {
      hash_unique: {
        user_password: userPassword,
        user_salt: userSalt
      }
    });
  };
  timestamp = async (): Promise<Timestamp> => {
    return this.client.queryContractSmart(this.contractAddress, {
      timestamp: {}
    });
  };
}