/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, Decimal, TokenUnverified, InstantiateMsg, Fee, CurrencyForTokenUnverified, Range, ExecuteMsg, QueryMsg, MigrateMsg, Addr, AddressConfig, Uint64, Token, CommonConfig, CurrencyForToken } from "./Hub.types";
export interface HubReadOnlyInterface {
  contractAddress: string;
  addressConfig: () => Promise<AddressConfig>;
  commonConfig: () => Promise<CommonConfig>;
  blockTime: () => Promise<Uint64>;
}
export class HubQueryClient implements HubReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.addressConfig = this.addressConfig.bind(this);
    this.commonConfig = this.commonConfig.bind(this);
    this.blockTime = this.blockTime.bind(this);
  }
  addressConfig = async (): Promise<AddressConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      address_config: {}
    });
  };
  commonConfig = async (): Promise<CommonConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      common_config: {}
    });
  };
  blockTime = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      block_time: {}
    });
  };
}
export interface HubInterface extends HubReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateAddressConfig: ({
    admin,
    chat,
    hashGenerator,
    judgeList,
    justice,
    offer,
    profile,
    trade,
    treasury
  }: {
    admin?: string;
    chat?: string;
    hashGenerator?: string;
    judgeList?: string[];
    justice?: string;
    offer?: string;
    profile?: string;
    trade?: string;
    treasury?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateCommonConfig: ({
    activeOffersLimit,
    activeTradesLimit,
    chatMaxLength,
    chatMaxMsgSequence,
    chatMaxSymbolsPerMsg,
    disputeFee,
    disputeQuorum,
    joinDisputeTimer,
    stablecoin,
    tradeDisputeTimer,
    tradeExpirationTimer,
    tradeFee,
    tradeLimit
  }: {
    activeOffersLimit?: number;
    activeTradesLimit?: number;
    chatMaxLength?: number;
    chatMaxMsgSequence?: number;
    chatMaxSymbolsPerMsg?: number;
    disputeFee?: Fee;
    disputeQuorum?: number;
    joinDisputeTimer?: number;
    stablecoin?: CurrencyForTokenUnverified;
    tradeDisputeTimer?: number;
    tradeExpirationTimer?: number;
    tradeFee?: Fee;
    tradeLimit?: Range;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  acceptAdminRole: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class HubClient extends HubQueryClient implements HubInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateAddressConfig = this.updateAddressConfig.bind(this);
    this.updateCommonConfig = this.updateCommonConfig.bind(this);
    this.acceptAdminRole = this.acceptAdminRole.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
  }
  updateAddressConfig = async ({
    admin,
    chat,
    hashGenerator,
    judgeList,
    justice,
    offer,
    profile,
    trade,
    treasury
  }: {
    admin?: string;
    chat?: string;
    hashGenerator?: string;
    judgeList?: string[];
    justice?: string;
    offer?: string;
    profile?: string;
    trade?: string;
    treasury?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_address_config: {
        admin,
        chat,
        hash_generator: hashGenerator,
        judge_list: judgeList,
        justice,
        offer,
        profile,
        trade,
        treasury
      }
    }, fee, memo, _funds);
  };
  updateCommonConfig = async ({
    activeOffersLimit,
    activeTradesLimit,
    chatMaxLength,
    chatMaxMsgSequence,
    chatMaxSymbolsPerMsg,
    disputeFee,
    disputeQuorum,
    joinDisputeTimer,
    stablecoin,
    tradeDisputeTimer,
    tradeExpirationTimer,
    tradeFee,
    tradeLimit
  }: {
    activeOffersLimit?: number;
    activeTradesLimit?: number;
    chatMaxLength?: number;
    chatMaxMsgSequence?: number;
    chatMaxSymbolsPerMsg?: number;
    disputeFee?: Fee;
    disputeQuorum?: number;
    joinDisputeTimer?: number;
    stablecoin?: CurrencyForTokenUnverified;
    tradeDisputeTimer?: number;
    tradeExpirationTimer?: number;
    tradeFee?: Fee;
    tradeLimit?: Range;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_common_config: {
        active_offers_limit: activeOffersLimit,
        active_trades_limit: activeTradesLimit,
        chat_max_length: chatMaxLength,
        chat_max_msg_sequence: chatMaxMsgSequence,
        chat_max_symbols_per_msg: chatMaxSymbolsPerMsg,
        dispute_fee: disputeFee,
        dispute_quorum: disputeQuorum,
        join_dispute_timer: joinDisputeTimer,
        stablecoin,
        trade_dispute_timer: tradeDisputeTimer,
        trade_expiration_timer: tradeExpirationTimer,
        trade_fee: tradeFee,
        trade_limit: tradeLimit
      }
    }, fee, memo, _funds);
  };
  acceptAdminRole = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      accept_admin_role: {}
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
}