/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint128, Decimal, TokenUnverified, InstantiateMsg, Fee, CurrencyForTokenUnverified, Range, ExecuteMsg, QueryMsg, MigrateMsg, Addr, AddressConfig, Uint64, Token, CommonConfig, CurrencyForToken } from "./Hub.types";
export interface HubMsg {
  contractAddress: string;
  sender: string;
  updateAddressConfig: ({
    admin,
    chat,
    hashGenerator,
    judgeList,
    justice,
    offer,
    profile,
    trade,
    treasury
  }: {
    admin?: string;
    chat?: string;
    hashGenerator?: string;
    judgeList?: string[];
    justice?: string;
    offer?: string;
    profile?: string;
    trade?: string;
    treasury?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateCommonConfig: ({
    activeOffersLimit,
    activeTradesLimit,
    chatMaxLength,
    chatMaxMsgSequence,
    chatMaxSymbolsPerMsg,
    disputeFee,
    disputeQuorum,
    joinDisputeTimer,
    stablecoin,
    tradeDisputeTimer,
    tradeExpirationTimer,
    tradeFee,
    tradeLimit
  }: {
    activeOffersLimit?: number;
    activeTradesLimit?: number;
    chatMaxLength?: number;
    chatMaxMsgSequence?: number;
    chatMaxSymbolsPerMsg?: number;
    disputeFee?: Fee;
    disputeQuorum?: number;
    joinDisputeTimer?: number;
    stablecoin?: CurrencyForTokenUnverified;
    tradeDisputeTimer?: number;
    tradeExpirationTimer?: number;
    tradeFee?: Fee;
    tradeLimit?: Range;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  acceptAdminRole: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class HubMsgComposer implements HubMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateAddressConfig = this.updateAddressConfig.bind(this);
    this.updateCommonConfig = this.updateCommonConfig.bind(this);
    this.acceptAdminRole = this.acceptAdminRole.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
  }
  updateAddressConfig = ({
    admin,
    chat,
    hashGenerator,
    judgeList,
    justice,
    offer,
    profile,
    trade,
    treasury
  }: {
    admin?: string;
    chat?: string;
    hashGenerator?: string;
    judgeList?: string[];
    justice?: string;
    offer?: string;
    profile?: string;
    trade?: string;
    treasury?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_address_config: {
            admin,
            chat,
            hash_generator: hashGenerator,
            judge_list: judgeList,
            justice,
            offer,
            profile,
            trade,
            treasury
          }
        })),
        funds: _funds
      })
    };
  };
  updateCommonConfig = ({
    activeOffersLimit,
    activeTradesLimit,
    chatMaxLength,
    chatMaxMsgSequence,
    chatMaxSymbolsPerMsg,
    disputeFee,
    disputeQuorum,
    joinDisputeTimer,
    stablecoin,
    tradeDisputeTimer,
    tradeExpirationTimer,
    tradeFee,
    tradeLimit
  }: {
    activeOffersLimit?: number;
    activeTradesLimit?: number;
    chatMaxLength?: number;
    chatMaxMsgSequence?: number;
    chatMaxSymbolsPerMsg?: number;
    disputeFee?: Fee;
    disputeQuorum?: number;
    joinDisputeTimer?: number;
    stablecoin?: CurrencyForTokenUnverified;
    tradeDisputeTimer?: number;
    tradeExpirationTimer?: number;
    tradeFee?: Fee;
    tradeLimit?: Range;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_common_config: {
            active_offers_limit: activeOffersLimit,
            active_trades_limit: activeTradesLimit,
            chat_max_length: chatMaxLength,
            chat_max_msg_sequence: chatMaxMsgSequence,
            chat_max_symbols_per_msg: chatMaxSymbolsPerMsg,
            dispute_fee: disputeFee,
            dispute_quorum: disputeQuorum,
            join_dispute_timer: joinDisputeTimer,
            stablecoin,
            trade_dispute_timer: tradeDisputeTimer,
            trade_expiration_timer: tradeExpirationTimer,
            trade_fee: tradeFee,
            trade_limit: tradeLimit
          }
        })),
        funds: _funds
      })
    };
  };
  acceptAdminRole = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_admin_role: {}
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
}