/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export type TokenUnverified = {
  native: {
    denom: string;
  };
} | {
  cw20: {
    address: string;
  };
};
export interface InstantiateMsg {
  active_offers_limit?: number | null;
  active_trades_limit?: number | null;
  admin?: string | null;
  chat?: string | null;
  chat_max_length?: number | null;
  chat_max_msg_sequence?: number | null;
  chat_max_symbols_per_msg?: number | null;
  dispute_fee?: Fee | null;
  dispute_quorum?: number | null;
  hash_generator?: string | null;
  join_dispute_timer?: number | null;
  judge_list?: string[] | null;
  justice?: string | null;
  offer?: string | null;
  profile?: string | null;
  stablecoin?: CurrencyForTokenUnverified | null;
  trade?: string | null;
  trade_dispute_timer?: number | null;
  trade_expiration_timer?: number | null;
  trade_fee?: Fee | null;
  trade_limit?: Range | null;
  treasury?: string | null;
}
export interface Fee {
  base: Uint128;
  rate: Decimal;
}
export interface CurrencyForTokenUnverified {
  decimals: number;
  token: TokenUnverified;
}
export interface Range {
  max: Uint128;
  min: Uint128;
}
export type ExecuteMsg = {
  update_address_config: {
    admin?: string | null;
    chat?: string | null;
    hash_generator?: string | null;
    judge_list?: string[] | null;
    justice?: string | null;
    offer?: string | null;
    profile?: string | null;
    trade?: string | null;
    treasury?: string | null;
  };
} | {
  update_common_config: {
    active_offers_limit?: number | null;
    active_trades_limit?: number | null;
    chat_max_length?: number | null;
    chat_max_msg_sequence?: number | null;
    chat_max_symbols_per_msg?: number | null;
    dispute_fee?: Fee | null;
    dispute_quorum?: number | null;
    join_dispute_timer?: number | null;
    stablecoin?: CurrencyForTokenUnverified | null;
    trade_dispute_timer?: number | null;
    trade_expiration_timer?: number | null;
    trade_fee?: Fee | null;
    trade_limit?: Range | null;
  };
} | {
  accept_admin_role: {};
} | {
  pause: {};
} | {
  unpause: {};
};
export type QueryMsg = {
  address_config: {};
} | {
  common_config: {};
} | {
  block_time: {};
};
export interface MigrateMsg {
  version: string;
}
export type Addr = string;
export interface AddressConfig {
  admin: Addr;
  chat: Addr;
  hash_generator: Addr;
  judge_list: Addr[];
  justice: Addr;
  offer: Addr;
  profile: Addr;
  trade: Addr;
  treasury: Addr;
}
export type Uint64 = number;
export type Token = {
  native: {
    denom: string;
  };
} | {
  cw20: {
    address: Addr;
  };
};
export interface CommonConfig {
  active_offers_limit: number;
  active_trades_limit: number;
  chat_max_length: number;
  chat_max_msg_sequence: number;
  chat_max_symbols_per_msg: number;
  dispute_fee: Fee;
  dispute_quorum: number;
  join_dispute_timer: number;
  stablecoin: CurrencyForToken;
  trade_dispute_timer: number;
  trade_expiration_timer: number;
  trade_fee: Fee;
  trade_limit: Range;
}
export interface CurrencyForToken {
  decimals: number;
  token: Token;
}