/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, Addr, DisputeStatus, Dispute, VoteItem, ArrayOfTupleOfUint64AndDispute, Uint128 } from "./Justice.types";
export interface JusticeMsg {
  contractAddress: string;
  sender: string;
  requestDispute: ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  joinDispute: ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  vote: ({
    tradeId,
    winner
  }: {
    tradeId: number;
    winner: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  finalize: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claim: ({
    recipient
  }: {
    recipient?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  registerHub: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class JusticeMsgComposer implements JusticeMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.requestDispute = this.requestDispute.bind(this);
    this.joinDispute = this.joinDispute.bind(this);
    this.vote = this.vote.bind(this);
    this.finalize = this.finalize.bind(this);
    this.claim = this.claim.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  requestDispute = ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          request_dispute: {
            sender,
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  joinDispute = ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          join_dispute: {
            sender,
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  vote = ({
    tradeId,
    winner
  }: {
    tradeId: number;
    winner: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          vote: {
            trade_id: tradeId,
            winner
          }
        })),
        funds: _funds
      })
    };
  };
  finalize = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          finalize: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  claim = ({
    recipient
  }: {
    recipient?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim: {
            recipient
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  registerHub = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_hub: {}
        })),
        funds: _funds
      })
    };
  };
}