/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, QueryMsg, MigrateMsg, Addr, DisputeStatus, Dispute, VoteItem, ArrayOfTupleOfUint64AndDispute, Uint128 } from "./Justice.types";
export interface JusticeReadOnlyInterface {
  contractAddress: string;
  dispute: ({
    tradeId
  }: {
    tradeId: number;
  }) => Promise<Dispute>;
  disputeList: ({
    amount,
    startBefore
  }: {
    amount: number;
    startBefore?: number;
  }) => Promise<ArrayOfTupleOfUint64AndDispute>;
  fee: () => Promise<Uint128>;
}
export class JusticeQueryClient implements JusticeReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.dispute = this.dispute.bind(this);
    this.disputeList = this.disputeList.bind(this);
    this.fee = this.fee.bind(this);
  }
  dispute = async ({
    tradeId
  }: {
    tradeId: number;
  }): Promise<Dispute> => {
    return this.client.queryContractSmart(this.contractAddress, {
      dispute: {
        trade_id: tradeId
      }
    });
  };
  disputeList = async ({
    amount,
    startBefore
  }: {
    amount: number;
    startBefore?: number;
  }): Promise<ArrayOfTupleOfUint64AndDispute> => {
    return this.client.queryContractSmart(this.contractAddress, {
      dispute_list: {
        amount,
        start_before: startBefore
      }
    });
  };
  fee = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      fee: {}
    });
  };
}
export interface JusticeInterface extends JusticeReadOnlyInterface {
  contractAddress: string;
  sender: string;
  requestDispute: ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  joinDispute: ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  vote: ({
    tradeId,
    winner
  }: {
    tradeId: number;
    winner: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  finalize: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claim: ({
    recipient
  }: {
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerHub: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class JusticeClient extends JusticeQueryClient implements JusticeInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.requestDispute = this.requestDispute.bind(this);
    this.joinDispute = this.joinDispute.bind(this);
    this.vote = this.vote.bind(this);
    this.finalize = this.finalize.bind(this);
    this.claim = this.claim.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  requestDispute = async ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      request_dispute: {
        sender,
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  joinDispute = async ({
    sender,
    tradeId
  }: {
    sender: string;
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      join_dispute: {
        sender,
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  vote = async ({
    tradeId,
    winner
  }: {
    tradeId: number;
    winner: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      vote: {
        trade_id: tradeId,
        winner
      }
    }, fee, memo, _funds);
  };
  finalize = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      finalize: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  claim = async ({
    recipient
  }: {
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        recipient
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  registerHub = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_hub: {}
    }, fee, memo, _funds);
  };
}