/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  request_dispute: {
    sender: string;
    trade_id: number;
  };
} | {
  join_dispute: {
    sender: string;
    trade_id: number;
  };
} | {
  vote: {
    trade_id: number;
    winner: string;
  };
} | {
  finalize: {
    trade_id: number;
  };
} | {
  claim: {
    recipient?: string | null;
  };
} | {
  pause: {};
} | {
  unpause: {};
} | {
  register_hub: {};
};
export type QueryMsg = {
  dispute: {
    trade_id: number;
  };
} | {
  dispute_list: {
    amount: number;
    start_before?: number | null;
  };
} | {
  fee: {};
};
export interface MigrateMsg {
  version: string;
}
export type Addr = string;
export type DisputeStatus = ("requested" | "confirmed") | {
  resolved: Addr;
} | {
  finalized: Addr;
};
export interface Dispute {
  acceptor?: Addr | null;
  creation_date: number;
  creator: Addr;
  status: DisputeStatus;
  trade_id: number;
  vote_list: VoteItem[];
}
export interface VoteItem {
  judge: Addr;
  winner: Addr;
}
export type ArrayOfTupleOfUint64AndDispute = [number, Dispute][];
export type Uint128 = string;