/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, FiatCurrency, Uint128, OfferType, Decimal, OfferState, OfferCreateInfo, OfferUpdateInfo, QueryMsg, OfferOrder, MigrateMsg, Addr, OfferResponse, Offer, Profile, ArrayOfOfferResponse, Uint64 } from "./Offer.types";
export interface OfferReadOnlyInterface {
  contractAddress: string;
  offersCount: () => Promise<Uint64>;
  offer: ({
    id
  }: {
    id: number;
  }) => Promise<OfferResponse>;
  offersBy: ({
    fiatCurrency,
    last,
    limit,
    offerType,
    order
  }: {
    fiatCurrency: FiatCurrency;
    last?: number;
    limit: number;
    offerType: OfferType;
    order: OfferOrder;
  }) => Promise<ArrayOfOfferResponse>;
  offersByOwner: ({
    last,
    limit,
    owner
  }: {
    last?: number;
    limit: number;
    owner: string;
  }) => Promise<ArrayOfOfferResponse>;
}
export class OfferQueryClient implements OfferReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.offersCount = this.offersCount.bind(this);
    this.offer = this.offer.bind(this);
    this.offersBy = this.offersBy.bind(this);
    this.offersByOwner = this.offersByOwner.bind(this);
  }
  offersCount = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      offers_count: {}
    });
  };
  offer = async ({
    id
  }: {
    id: number;
  }): Promise<OfferResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      offer: {
        id
      }
    });
  };
  offersBy = async ({
    fiatCurrency,
    last,
    limit,
    offerType,
    order
  }: {
    fiatCurrency: FiatCurrency;
    last?: number;
    limit: number;
    offerType: OfferType;
    order: OfferOrder;
  }): Promise<ArrayOfOfferResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      offers_by: {
        fiat_currency: fiatCurrency,
        last,
        limit,
        offer_type: offerType,
        order
      }
    });
  };
  offersByOwner = async ({
    last,
    limit,
    owner
  }: {
    last?: number;
    limit: number;
    owner: string;
  }): Promise<ArrayOfOfferResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      offers_by_owner: {
        last,
        limit,
        owner
      }
    });
  };
}
export interface OfferInterface extends OfferReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createOffer: ({
    description,
    fiatCurrency,
    maxAmount,
    minAmount,
    offerType,
    rate
  }: {
    description?: string;
    fiatCurrency: FiatCurrency;
    maxAmount: Uint128;
    minAmount: Uint128;
    offerType: OfferType;
    rate: Decimal;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateOffer: ({
    description,
    id,
    maxAmount,
    minAmount,
    rate,
    state
  }: {
    description?: string;
    id: number;
    maxAmount: Uint128;
    minAmount: Uint128;
    rate: Decimal;
    state: OfferState;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerHub: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class OfferClient extends OfferQueryClient implements OfferInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createOffer = this.createOffer.bind(this);
    this.updateOffer = this.updateOffer.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  createOffer = async ({
    description,
    fiatCurrency,
    maxAmount,
    minAmount,
    offerType,
    rate
  }: {
    description?: string;
    fiatCurrency: FiatCurrency;
    maxAmount: Uint128;
    minAmount: Uint128;
    offerType: OfferType;
    rate: Decimal;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_offer: {
        description,
        fiat_currency: fiatCurrency,
        max_amount: maxAmount,
        min_amount: minAmount,
        offer_type: offerType,
        rate
      }
    }, fee, memo, _funds);
  };
  updateOffer = async ({
    description,
    id,
    maxAmount,
    minAmount,
    rate,
    state
  }: {
    description?: string;
    id: number;
    maxAmount: Uint128;
    minAmount: Uint128;
    rate: Decimal;
    state: OfferState;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_offer: {
        description,
        id,
        max_amount: maxAmount,
        min_amount: minAmount,
        rate,
        state
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  registerHub = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_hub: {}
    }, fee, memo, _funds);
  };
}