/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, FiatCurrency, Uint128, OfferType, Decimal, OfferState, OfferCreateInfo, OfferUpdateInfo, QueryMsg, OfferOrder, MigrateMsg, Addr, OfferResponse, Offer, Profile, ArrayOfOfferResponse, Uint64 } from "./Offer.types";
export interface OfferMsg {
  contractAddress: string;
  sender: string;
  createOffer: ({
    description,
    fiatCurrency,
    max_amount,
    min_amount,
    offerType,
    rate
  }: {
    description?: string;
    fiatCurrency: FiatCurrency;
    max_amount: Uint128;
    min_amount: Uint128;
    offerType: OfferType;
    rate: Decimal;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateOffer: ({
    description,
    id,
    max_amount,
    min_amount,
    rate,
    state
  }: {
    description?: string;
    id: number;
    max_amount: Uint128;
    min_amount: Uint128;
    rate: Decimal;
    state: OfferState;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  registerHub: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class OfferMsgComposer implements OfferMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createOffer = this.createOffer.bind(this);
    this.updateOffer = this.updateOffer.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  createOffer = ({
    description,
    fiat_currency,
    max_amount,
    min_amount,
    offer_type,
    rate
  }: {
    description?: string;
    fiat_currency: FiatCurrency;
    max_amount: Uint128;
    min_amount: Uint128;
    offer_type: OfferType;
    rate: Decimal;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_offer: {
            description,
            fiat_currency: fiat_currency,
            max_amount: max_amount,
            min_amount: min_amount,
            offer_type: offer_type,
            rate
          }
        })),
        funds: _funds
      })
    };
  };
  updateOffer = ({
    description,
    id,
    max_amount,
    min_amount,
    rate,
    state
  }: {
    description?: string;
    id: number;
    max_amount: Uint128;
    min_amount: Uint128;
    rate: Decimal;
    state: OfferState;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_offer: {
            description,
            id,
            max_amount: max_amount,
            min_amount: min_amount,
            rate,
            state
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  registerHub = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_hub: {}
        })),
        funds: _funds
      })
    };
  };
}