/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  update_contact: {
    profile_addr: string;
  };
} | {
  update_active_offers: {
    offer_state: OfferState;
    profile_addr: string;
  };
} | {
  update_trades_count: {
    dispute_winner?: string | null;
    profile_addr: string;
    trade_state: TradeState;
  };
} | {
  pause: {};
} | {
  unpause: {};
} | {
  register_hub: {};
};
export type OfferState = "active" | "paused" | "archive";
export type TradeState = "request_created" | "request_canceled" | "request_expired" | "request_accepted" | "escrow_funded" | "escrow_refunded" | "fiat_deposited" | "escrow_released" | "started_dispute" | "finalized_for_maker" | "finalized_for_taker";
export type QueryMsg = {
  profile: {
    addr: string;
  };
} | {
  profiles: {
    limit: number;
    start_at?: number | null;
  };
};
export interface MigrateMsg {
  version: string;
}
export type Addr = string;
export interface Profile {
  active_offers_count: number;
  active_trades_count: number;
  addr: Addr;
  created_at: number;
  last_trade: number;
  released_trades_count: number;
  total_dispute_count: number;
  total_trades_count: number;
  won_dispute_count: number;
}
export type ArrayOfProfile = Profile[];