/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, OfferState, TradeState, QueryMsg, MigrateMsg, Addr, Profile, ArrayOfProfile } from "./Profile.types";
export interface ProfileMsg {
  contractAddress: string;
  sender: string;
  updateContact: ({
    profileAddr
  }: {
    profileAddr: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateActiveOffers: ({
    offerState,
    profileAddr
  }: {
    offerState: OfferState;
    profileAddr: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateTradesCount: ({
    disputeWinner,
    profileAddr,
    tradeState
  }: {
    disputeWinner?: string;
    profileAddr: string;
    tradeState: TradeState;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  registerHub: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class ProfileMsgComposer implements ProfileMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateContact = this.updateContact.bind(this);
    this.updateActiveOffers = this.updateActiveOffers.bind(this);
    this.updateTradesCount = this.updateTradesCount.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  updateContact = ({
    profileAddr
  }: {
    profileAddr: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_contact: {
            profile_addr: profileAddr
          }
        })),
        funds: _funds
      })
    };
  };
  updateActiveOffers = ({
    offerState,
    profileAddr
  }: {
    offerState: OfferState;
    profileAddr: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_active_offers: {
            offer_state: offerState,
            profile_addr: profileAddr
          }
        })),
        funds: _funds
      })
    };
  };
  updateTradesCount = ({
    disputeWinner,
    profileAddr,
    tradeState
  }: {
    disputeWinner?: string;
    profileAddr: string;
    tradeState: TradeState;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_trades_count: {
            dispute_winner: disputeWinner,
            profile_addr: profileAddr,
            trade_state: tradeState
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  registerHub = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_hub: {}
        })),
        funds: _funds
      })
    };
  };
}