/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, OfferState, TradeState, QueryMsg, MigrateMsg, Addr, Profile, ArrayOfProfile } from "./Profile.types";
export interface ProfileReadOnlyInterface {
  contractAddress: string;
  profile: ({
    addr
  }: {
    addr: string;
  }) => Promise<Profile>;
  profiles: ({
    limit,
    startAt
  }: {
    limit: number;
    startAt?: number;
  }) => Promise<ArrayOfProfile>;
}
export class ProfileQueryClient implements ProfileReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.profile = this.profile.bind(this);
    this.profiles = this.profiles.bind(this);
  }
  profile = async ({
    addr
  }: {
    addr: string;
  }): Promise<Profile> => {
    return this.client.queryContractSmart(this.contractAddress, {
      profile: {
        addr
      }
    });
  };
  profiles = async ({
    limit,
    startAt
  }: {
    limit: number;
    startAt?: number;
  }): Promise<ArrayOfProfile> => {
    return this.client.queryContractSmart(this.contractAddress, {
      profiles: {
        limit,
        start_at: startAt
      }
    });
  };
}
export interface ProfileInterface extends ProfileReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateContact: ({
    profileAddr
  }: {
    profileAddr: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateActiveOffers: ({
    offerState,
    profileAddr
  }: {
    offerState: OfferState;
    profileAddr: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateTradesCount: ({
    disputeWinner,
    profileAddr,
    tradeState
  }: {
    disputeWinner?: string;
    profileAddr: string;
    tradeState: TradeState;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerHub: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ProfileClient extends ProfileQueryClient implements ProfileInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateContact = this.updateContact.bind(this);
    this.updateActiveOffers = this.updateActiveOffers.bind(this);
    this.updateTradesCount = this.updateTradesCount.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  updateContact = async ({
    profileAddr
  }: {
    profileAddr: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_contact: {
        profile_addr: profileAddr
      }
    }, fee, memo, _funds);
  };
  updateActiveOffers = async ({
    offerState,
    profileAddr
  }: {
    offerState: OfferState;
    profileAddr: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_active_offers: {
        offer_state: offerState,
        profile_addr: profileAddr
      }
    }, fee, memo, _funds);
  };
  updateTradesCount = async ({
    disputeWinner,
    profileAddr,
    tradeState
  }: {
    disputeWinner?: string;
    profileAddr: string;
    tradeState: TradeState;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_trades_count: {
        dispute_winner: disputeWinner,
        profile_addr: profileAddr,
        trade_state: tradeState
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  registerHub = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_hub: {}
    }, fee, memo, _funds);
  };
}