/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  create_trade: NewTrade;
} | {
  accept_request: {
    trade_id: number;
  };
} | {
  fund_escrow: {
    trade_id: number;
  };
} | {
  refund_escrow: {
    trade_id: number;
  };
} | {
  release_escrow: {
    trade_id: number;
  };
} | {
  set_fiat_deposited_state: {
    trade_id: number;
  };
} | {
  cancel_request: {
    trade_id: number;
  };
} | {
  request_dispute: {
    trade_id: number;
  };
} | {
  join_dispute: {
    trade_id: number;
  };
} | {
  finalize_dispute: {
    trade_id: number;
  };
} | {
  pause: {};
} | {
  unpause: {};
} | {
  register_hub: {};
};
export type Uint128 = string;
export type Binary = string;
export type Addr = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface NewTrade {
  amount: Uint128;
  offer_id: number;
  taker: Addr;
}
export type QueryMsg = {
  trade: {
    id: number;
  };
} | {
  trades: {
    last?: number | null;
    limit: number;
    user: string;
  };
} | {
  model_trades: {
    user: string;
  };
};
export interface MigrateMsg {
  version: string;
}
export type FiatCurrency = "a_e_d" | "a_f_n" | "a_l_l" | "a_m_d" | "a_n_g" | "a_o_a" | "a_r_s" | "a_u_d" | "a_w_g" | "a_z_n" | "b_a_m" | "b_b_d" | "b_d_t" | "b_g_n" | "b_h_d" | "b_i_f" | "b_m_d" | "b_n_d" | "b_o_b" | "b_r_l" | "b_s_d" | "b_t_n" | "b_w_p" | "b_y_r" | "b_z_d" | "c_a_d" | "c_d_f" | "c_h_f" | "c_l_p" | "c_n_y" | "c_o_p" | "c_o_u" | "c_r_c" | "c_u_c" | "c_u_p" | "c_v_e" | "c_z_k" | "d_j_f" | "d_k_k" | "d_o_p" | "d_z_d" | "e_g_p" | "e_r_n" | "e_t_b" | "e_u_r" | "f_j_d" | "f_k_p" | "g_b_p" | "g_e_l" | "g_h_s" | "g_i_p" | "g_m_d" | "g_n_f" | "g_t_q" | "g_y_d" | "h_k_d" | "h_n_l" | "h_r_k" | "h_t_g" | "h_u_f" | "i_d_r" | "i_l_s" | "i_n_r" | "i_q_d" | "i_r_r" | "i_s_k" | "j_m_d" | "j_o_d" | "j_p_y" | "k_e_s" | "k_g_s" | "k_h_r" | "k_m_f" | "k_p_w" | "k_r_w" | "k_w_d" | "k_y_d" | "k_z_t" | "l_a_k" | "l_b_p" | "l_k_r" | "l_r_d" | "l_s_l" | "l_t_l" | "l_v_l" | "l_y_d" | "m_a_d" | "m_d_l" | "m_g_a" | "m_k_d" | "m_m_k" | "m_n_t" | "m_o_p" | "m_r_o" | "m_u_r" | "m_v_r" | "m_w_k" | "m_x_n" | "m_y_r" | "m_z_n" | "n_a_d" | "n_g_n" | "n_i_o" | "n_o_k" | "n_p_r" | "n_z_d" | "o_m_r" | "p_a_b" | "p_e_n" | "p_g_k" | "p_h_p" | "p_k_r" | "p_l_n" | "p_y_g" | "q_a_r" | "r_o_n" | "r_s_d" | "r_u_b" | "r_w_f" | "s_a_r" | "s_b_d" | "s_c_r" | "s_d_g" | "s_e_k" | "s_g_d" | "s_h_p" | "s_l_l" | "s_o_s" | "s_r_d" | "s_s_p" | "s_t_d" | "s_y_p" | "s_z_l" | "t_h_b" | "t_j_s" | "t_m_t" | "t_n_d" | "t_o_p" | "t_r_y" | "t_t_d" | "t_w_d" | "t_z_s" | "u_a_h" | "u_g_x" | "u_s_d" | "u_y_u" | "u_z_s" | "v_e_s" | "v_n_d" | "v_u_v" | "w_s_t" | "x_c_d" | "y_e_r" | "z_a_r" | "z_m_w";
export type Decimal = string;
export type TradeState = "request_created" | "request_canceled" | "request_expired" | "request_accepted" | "escrow_funded" | "escrow_refunded" | "fiat_deposited" | "escrow_released" | "started_dispute" | "finalized_for_maker" | "finalized_for_taker";
export interface QueryModelTradesResponse {
  trader: Trade[];
}
export interface Trade {
  addr: Addr;
  buyer: Addr;
  created_at: number;
  enables_dispute_at?: number | null;
  expires_at?: number | null;
  fiat: FiatCurrency;
  fiat_amount: Decimal;
  id: number;
  offer_contract: Addr;
  offer_id: number;
  seller: Addr;
  stablecoin_amount: Uint128;
  state: TradeState;
  state_history: TradeStateItem[];
}
export interface TradeStateItem {
  actor: Addr;
  state: TradeState;
  timestamp: number;
}
export type OfferType = "buy" | "sell";
export type OfferState = "active" | "paused" | "archive";
export interface TradeInfo {
  offer: OfferResponse;
  trade: TradeResponse;
}
export interface OfferResponse {
  offer: Offer;
  profile: Profile;
}
export interface Offer {
  description?: string | null;
  fiat_currency: FiatCurrency;
  id: number;
  max_amount: Uint128;
  min_amount: Uint128;
  offer_type: OfferType;
  owner: Addr;
  rate: Decimal;
  state: OfferState;
  timestamp: number;
}
export interface Profile {
  active_offers_count: number;
  active_trades_count: number;
  addr: Addr;
  created_at: number;
  last_trade: number;
  released_trades_count: number;
  total_dispute_count: number;
  total_trades_count: number;
  won_dispute_count: number;
}
export interface TradeResponse {
  addr: Addr;
  buyer: Addr;
  created_at: number;
  enables_dispute_at?: number | null;
  expires_at?: number | null;
  fiat: FiatCurrency;
  fiat_amount: Decimal;
  id: number;
  offer_contract: Addr;
  offer_id: number;
  seller: Addr;
  stablecoin_amount: Uint128;
  state: TradeState;
  state_history: TradeStateItem[];
}
export type ArrayOfTradeInfo = TradeInfo[];