/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, Addr, Cw20ReceiveMsg, NewTrade, QueryMsg, MigrateMsg, FiatCurrency, Decimal, TradeState, QueryModelTradesResponse, Trade, TradeStateItem, OfferType, OfferState, TradeInfo, OfferResponse, Offer, Profile, TradeResponse, ArrayOfTradeInfo } from "./Trade.types";
export interface TradeMsg {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createTrade: ({
    amount,
    offerId,
    taker
  }: {
    amount: Uint128;
    offerId: number;
    taker: Addr;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  acceptRequest: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  fundEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  refundEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  releaseEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setFiatDepositedState: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  cancelRequest: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  requestDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  joinDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  finalizeDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  registerHub: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class TradeMsgComposer implements TradeMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.createTrade = this.createTrade.bind(this);
    this.acceptRequest = this.acceptRequest.bind(this);
    this.fundEscrow = this.fundEscrow.bind(this);
    this.refundEscrow = this.refundEscrow.bind(this);
    this.releaseEscrow = this.releaseEscrow.bind(this);
    this.setFiatDepositedState = this.setFiatDepositedState.bind(this);
    this.cancelRequest = this.cancelRequest.bind(this);
    this.requestDispute = this.requestDispute.bind(this);
    this.joinDispute = this.joinDispute.bind(this);
    this.finalizeDispute = this.finalizeDispute.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  receive = ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          receive: {
            amount,
            msg,
            sender
          }
        })),
        funds: _funds
      })
    };
  };
  createTrade = ({
    amount,
    offerId,
    taker
  }: {
    amount: Uint128;
    offerId: number;
    taker: Addr;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_trade: {
            amount,
            offer_id: offerId,
            taker
          }
        })),
        funds: _funds
      })
    };
  };
  acceptRequest = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_request: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  fundEscrow = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          fund_escrow: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  refundEscrow = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          refund_escrow: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  releaseEscrow = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          release_escrow: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  setFiatDepositedState = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_fiat_deposited_state: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  cancelRequest = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          cancel_request: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  requestDispute = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          request_dispute: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  joinDispute = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          join_dispute: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  finalizeDispute = ({
    tradeId
  }: {
    tradeId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          finalize_dispute: {
            trade_id: tradeId
          }
        })),
        funds: _funds
      })
    };
  };
  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  registerHub = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_hub: {}
        })),
        funds: _funds
      })
    };
  };
}