/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, Addr, Cw20ReceiveMsg, NewTrade, QueryMsg, MigrateMsg, FiatCurrency, Decimal, TradeState, QueryModelTradesResponse, Trade, TradeStateItem, OfferType, OfferState, TradeInfo, OfferResponse, Offer, Profile, TradeResponse, ArrayOfTradeInfo } from "./Trade.types";
export interface TradeReadOnlyInterface {
  contractAddress: string;
  trade: ({
    id
  }: {
    id: number;
  }) => Promise<TradeInfo>;
  trades: ({
    last,
    limit,
    user
  }: {
    last?: number;
    limit: number;
    user: string;
  }) => Promise<ArrayOfTradeInfo>;
  modelTrades: ({
    user
  }: {
    user: string;
  }) => Promise<QueryModelTradesResponse>;
}
export class TradeQueryClient implements TradeReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.trade = this.trade.bind(this);
    this.trades = this.trades.bind(this);
    this.modelTrades = this.modelTrades.bind(this);
  }
  trade = async ({
    id
  }: {
    id: number;
  }): Promise<TradeInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      trade: {
        id
      }
    });
  };
  trades = async ({
    last,
    limit,
    user
  }: {
    last?: number;
    limit: number;
    user: string;
  }): Promise<ArrayOfTradeInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      trades: {
        last,
        limit,
        user
      }
    });
  };
  modelTrades = async ({
    user
  }: {
    user: string;
  }): Promise<QueryModelTradesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      model_trades: {
        user
      }
    });
  };
}
export interface TradeInterface extends TradeReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createTrade: ({
    amount,
    offerId,
    taker
  }: {
    amount: Uint128;
    offerId: number;
    taker: Addr;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  acceptRequest: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  fundEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  refundEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  releaseEscrow: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  setFiatDepositedState: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  cancelRequest: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  requestDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  joinDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  finalizeDispute: ({
    tradeId
  }: {
    tradeId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  pause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unpause: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  registerHub: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class TradeClient extends TradeQueryClient implements TradeInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.createTrade = this.createTrade.bind(this);
    this.acceptRequest = this.acceptRequest.bind(this);
    this.fundEscrow = this.fundEscrow.bind(this);
    this.refundEscrow = this.refundEscrow.bind(this);
    this.releaseEscrow = this.releaseEscrow.bind(this);
    this.setFiatDepositedState = this.setFiatDepositedState.bind(this);
    this.cancelRequest = this.cancelRequest.bind(this);
    this.requestDispute = this.requestDispute.bind(this);
    this.joinDispute = this.joinDispute.bind(this);
    this.finalizeDispute = this.finalizeDispute.bind(this);
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.registerHub = this.registerHub.bind(this);
  }
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee, memo, _funds);
  };
  createTrade = async ({
    amount,
    offerId,
    taker
  }: {
    amount: Uint128;
    offerId: number;
    taker: Addr;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_trade: {
        amount,
        offer_id: offerId,
        taker
      }
    }, fee, memo, _funds);
  };
  acceptRequest = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      accept_request: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  fundEscrow = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      fund_escrow: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  refundEscrow = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      refund_escrow: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  releaseEscrow = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      release_escrow: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  setFiatDepositedState = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      set_fiat_deposited_state: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  cancelRequest = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_request: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  requestDispute = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      request_dispute: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  joinDispute = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      join_dispute: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  finalizeDispute = async ({
    tradeId
  }: {
    tradeId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      finalize_dispute: {
        trade_id: tradeId
      }
    }, fee, memo, _funds);
  };
  pause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      pause: {}
    }, fee, memo, _funds);
  };
  unpause = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unpause: {}
    }, fee, memo, _funds);
  };
  registerHub = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_hub: {}
    }, fee, memo, _funds);
  };
}